services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./src/.env
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/bouncer_bot
      - NODE_ENV=production
    volumes:
      - ./assets:/app/assets
    restart: unless-stopped
    networks:
      - bot-network

  db:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 4s
      timeout: 4s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_DATABASE=bouncer_bot
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - bot-network

volumes:
  mysql_data:

networks:
  bot-network:
    driver: bridge